GAUNTLET_PROJECTS = [
    {
        "id": "fsp-agentic-scheduler",
        "name": "FSP Scheduler",
        "company": "Flight Schedule Pro",
        "stack": "TypeScript + React",
        "port": 3001,
        "estimated_minutes": 180,
        "github_url": "https://github.com/lakshmipunukollu-ai/fsp-agentic-scheduler",
    },
    {
        "id": "replicated-k8s-analyzer",
        "name": "K8s Analyzer",
        "company": "Replicated",
        "stack": "Python + Next.js",
        "port": 3002,
        "estimated_minutes": 150,
        "github_url": "https://github.com/lakshmipunukollu-ai/replicated-k8s-analyzer",
    },
    {
        "id": "servicecore-timetracking",
        "name": "Time Tracking",
        "company": "ServiceCore",
        "stack": "Angular + Node",
        "port": 3003,
        "estimated_minutes": 120,
        "github_url": "https://github.com/lakshmipunukollu-ai/servicecore-timetracking",
    },
    {
        "id": "zapier-triggers-api",
        "name": "Triggers API",
        "company": "Zapier",
        "stack": "Python + FastAPI + Redis",
        "port": 3004,
        "estimated_minutes": 90,
        "github_url": "https://github.com/lakshmipunukollu-ai/zapier-triggers-api",
    },
    {
        "id": "st6-weekly-commit",
        "name": "Weekly Commit",
        "company": "ST6",
        "stack": "Java 21 + React",
        "port": 8081,
        "estimated_minutes": 210,
        "github_url": "https://github.com/lakshmipunukollu-ai/st6-weekly-commit",
    },
    {
        "id": "zeropath-security-scanner",
        "name": "Security Scanner",
        "company": "ZeroPath",
        "stack": "Python + React",
        "port": 3006,
        "estimated_minutes": 150,
        "github_url": "https://github.com/lakshmipunukollu-ai/zeropath-security-scanner",
    },
    {
        "id": "medbridge-health-coach",
        "name": "Health Coach",
        "company": "Medbridge",
        "stack": "Python + LangGraph",
        "port": 3007,
        "estimated_minutes": 140,
        "github_url": "https://github.com/lakshmipunukollu-ai/medbridge-health-coach",
    },
    {
        "id": "companycam-content-detection",
        "name": "Content Detection",
        "company": "CompanyCam",
        "stack": "Python + YOLO + React",
        "port": 3008,
        "estimated_minutes": 130,
        "github_url": "https://github.com/lakshmipunukollu-ai/companycam-content-detection",
    },
    {
        "id": "upstream-ecommerce",
        "name": "E-commerce",
        "company": "Upstream Literacy",
        "stack": "Django + React + Stripe",
        "port": 3009,
        "estimated_minutes": 150,
        "github_url": "https://github.com/lakshmipunukollu-ai/upstream-ecommerce",
    },
]
